# Generated by Django 5.2 on 2025-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('pimages', models.ImageField(upload_to='uploads', verbose_name='Default.jpg')),
                ('ProductCategory', models.ManyToManyField(to='base.productcategory')),
            ],
        ),
    ]
