# Generated by Django 5.2 on 2025-05-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='Trending',
            field=models.BooleanField(default=False),
        ),
    ]
